version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: my_express_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm start

volumes:
  mongo-data:
